import "../styles/main.css";
import { Inter, Raleway } from "@/utils/fonts";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Kandinsky",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Inter.variable} ${Raleway.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
